version: '3.5'
services:
  demoserver:
    image: tsmean/server:${TRAVIS_BUILD_NUMBER}
    deploy:
      restart_policy:
        max_attempts: 3
      replicas: 1
      labels:
        - "traefik.frontend.rule=Host:demoserver.tsmean.com"
        - "traefik.port=4242"
        - "traefik.docker.network=traefik"
    ports:
      - "4242:4242"
    networks:
      - traefik
networks:
  traefik:
    external: true
